language: node_js
node_js:
  - "6"
  - "4"
install:
  - npm install
script:
  - npm run cover
  - npm run build

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
