language: node_js
node_js:
  - "6"
  - "4"
install:
  - npm install
script:
  - npm run coverage
  - npm run build
  - npm run build:commonjs

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
